# This config.toml is used to configure the examples. See nrf52840-examples\README.md.

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"
rustflags = ["-C", "linker=flip-link"]

[build]
# (`thumbv6m-*` is compatible with all ARM Cortex-M chips but using the right
# target improves performance)
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"

[alias]
bnrf = "build --package nrf52840-adxl355-embassy-example"
rnrfspi = "run --package nrf52840-adxl355-embassy-example --bin nrf52840_spi"
rnrfi2c = "run --package nrf52840-adxl355-embassy-example --bin nrf52840_i2c_async"
